name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run Debug Mode Tests
      run: make test DEBUG=1
    - name: Run Release Mode Tests
      run: make test
